packages:
  - app/*
  - package/*
  - playground/*
  - plugin/xd/*
  - script/*

autoInstallPeers: true

catalog:
  '@types/fs-extra': ^11.0.4
  '@types/node': 24.0.10
  '@types/yargs': ^17.0.33
  chokidar: ^4.0.3
  fs-extra: ^11.3.0
  tsx: ^4.20.3
  typescript: ~5.8.3
  unbuild: ^3.5.0
  vite: ^7.0.0
  yargs: ^18.0.0

ignoreWorkspaceRootCheck: true

shamefullyHoist: true

strictPeerDependencies: false
