packages:
  - 'app/*'
  - 'package/*'
  - 'plugin/xd/*'
  - 'script/*'

catalog:
  '@types/fs-extra': ^11.0.4
  '@types/node': ^24.0.10
  '@vitejs/plugin-vue': ^6.0.0
  '@vue/tsconfig': ^0.7.0
  '@types/yargs': ^17.0.33
  chokidar: ^4.0.3
  fs-extra: ^11.3.0
  tsx: ^4.20.3
  typescript: ~5.8.3
  unbuild: ^3.5.0
  vite: ^7.0.0
  vue: ^3.5.17
  vue-tsc: ^2.2.10
  yargs: ^18.0.0

# 自動安裝對等依賴
autoInstallPeers: true
# 忽略工作區根目錄檢查
ignoreWorkspaceRootCheck: true
# 啟用依賴提升
shamefullyHoist: true
# 關閉嚴格的對等依賴檢查
strictPeerDependencies: false

#onlyBuiltDependencies: